if (True):
    raise Exception("Failed purposefully")
